backend/pinstore/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'DashboardController@index')->name('dashboard');
Route::get('transactions/{id}/set-status','TransactionController@status')->name('transactions.status');
Route::get('products/{id}/gallery','ProductController@gallery')->name('products.gallery');
Route::resource('products', 'ProductController');
Route::resource('product-galleries','ProductGalleryController');
Route::resource('transactions','TransactionController');

backend/pinstore/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    protected $fillable = ['name','type','price','description','slug','quantity'];

    public function galleries(){
        return $this->hasMany(ProductGallery::class,'products_id');
    }

    public function details(){
        return $this->hasMany(TransactionDetail::class,'products_id');
    }
}

backend/pinstore/app/Http/Controllers/API/ProductController.php
<?php

namespace App\Http\Controllers\API;

use App\Product;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function all(Request $request){
        $id = $request->input('id');
        $slug = $request->input('slug');
        $limit = $request->input('limit',6);
        $name = $request->input('name');
        $type = $request->input('type');
        $price_from = $request->input('price_from');
        $price_to = $request->input('price_to');

        if($id){
            $product_id = Product::with('galleries')->find($id);
    
            if($product_id)
                return ResponseFormatter::success($product_id,'Data product berhasil di ambil');
            else
                return ResponseFormatter::error(null,'Data product tidak ada',404);
        }

        if($slug){
            $product_slug = Product::with('galleries')->where('slug',$slug)->first();

            if($product_slug)
                return ResponseFormatter::success($product_slug,'Data product berhasil di ambil');
            else
                return ResponseFormatter::error(null,'Data product tidak ada',404);
        }

        $product = Product::with('galleries');

        if($name){
            $product->where('name','like','%'.$name.'%');
        }
        if($type){
            $product->where('type','like','%'.$type.'%');
        }
        if($price_from){
            $product->where('price','>=',$price_from);
        }
        if($price_to){
            $product->where('price','<=',$price_to);
        }

        return ResponseFormatter::success(
            $product->paginate($limit),
            'Data berhasil diambil'
        );


    }
}

backend/pinstore/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Product;
use App\ProductGallery;
use App\Http\Requests\ProductRequest;
class ProductController extends Controller
{
       /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index(){
        $products = Product::all();
        return view('pages.products.index',compact('products'));
    }

    public function create(){
        return view('pages.products.create');
    }

    public function store(ProductRequest $request){
        $data = $request->all();
        $data['slug'] = Str::slug($request->name, '-');

        Product::create($data);

        return redirect()->route('products.index');
    }

    public function edit($id){
        $product = Product::findOrFail($id);
        return view('pages.products.edit',compact('product'));
    }

    public function destroy($id){
        $products = Product::findOrFail($id)->delete();
        $gallery = ProductGallery::where('products_id',$id)->delete();
        return redirect()->route('products.index');
    }

    public function update(ProductRequest $request, $id){
        $data = Product::findOrFail($id);
        $data['slug'] = Str::slug($request->name, '-');

        $data->update($request->all());

        return redirect()->route('products.index');
    }
    public function gallery($id){
        $items = ProductGallery::with('product')->where('products_id',$id)->get();
        return view('pages.products.gallery',compact('items'));
    }
}

backend/pinstore/resources/views/pages/products/create.blade.php
@extends('layouts.default')
@section('title','Tambah Barang')
@section('content')

   <div class="card">
       <div class="card-header"><strong>Tambah Barang</strong></div>
   </div>
   <div class="card-body card-block">
       <form action="{{ route('products.store') }}" method="POST">
           @csrf
           <div class="form-group">
               <label for="name" class="form-control-label">Nama Barang</label>
               <input type="text" id="name" name="name" value="{{ old('name') }}" class="form-control @error('name') is-invalid @enderror">
               @error('name')
                   <div class="text-muted text-danger">{{ $message }}</div>
               @enderror
           </div>

           <div class="form-group">
                <label for="type" class="form-control-label">Tipe Barang</label>
                <input type="text" id="type" name="type" value="{{ old('type') }}" class="form-control @error('type') is-invalid @enderror">
                @error('type')
                   <div class="text-muted text-danger">{{ $message }}</div>
               @enderror
            </div>

            <div class="form-group">
                <label for="price" class="form-control-label">Harga Barang</label>
                <input type="number" id="price" name="price" value="{{ old('price') }}" class="form-control @error('price') is-invalid @enderror">
                @error('price')
                   <div class="text-muted text-danger">{{ $message }}</div>
               @enderror
            </div>


            <div class="form-group">
                <label for="quantity" class="form-control-label">Kuantitas Barang</label>
                <input type="number" id="quantity" name="quantity" value="{{ old('quantity') }}" class="form-control @error('quantity') is-invalid @enderror">
                @error('quantity')
                   <div class="text-muted text-danger">{{ $message }}</div>
               @enderror
            </div>


        <div class="form-group">
            <label for="description" class="form-control-label">Deskripsi Barang</label>
            <textarea type="text" id="description" name="description" class="form-control ckeditor @error('description') is-invalid @enderror">{{ old('description') }}</textarea>
            @error('description')
                   <div class="text-muted text-danger">{{ $message }}</div>
               @enderror
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Tambah Barang</button>
        </div>
       </form>
   </div>

@endsection

backend/pinstore/resources/views/pages/products/edit.blade.php
@extends('layouts.default')
@section('title','Edit Barang')
@section('content')

   <div class="card">
       <div class="card-header"><strong>Edit Barang</strong></div>
   </div>
   <div class="card-body card-block">
       <form action="{{ route('products.update',$product->id) }}" method="POST">
        @method('PUT')
           @csrf
           <div class="form-group">
               <label for="name" class="form-control-label">Nama Barang</label>
               <input type="text" id="name" name="name" value="{{ old('name') ?? $product->name }}" class="form-control @error('name') is-invalid @enderror">
               @error('name')
                   <div class="text-muted">{{ $message }}</div>
               @enderror
           </div>

           <div class="form-group">
                <label for="type" class="form-control-label">Tipe Barang</label>
                <input type="text" id="type" name="type" value="{{ old('type') ?? $product->type  }}" class="form-control @error ('type') is-invalid @enderror">
                @error('type')
                   <div class="text-muted">{{ $message }}</div>
               @enderror
            </div>

            <div class="form-group">
                <label for="price" class="form-control-label">Harga Barang</label>
                <input type="number" id="price" name="price" value="{{ old('price') ?? $product->price  }}" class="form-control @error ('price') is-invalid @enderror">
                @error('price')
                   <div class="text-muted">{{ $message }}</div>
               @enderror
            </div>


            <div class="form-group">
                <label for="quantity" class="form-control-label">Kuantitas Barang</label>
                <input type="number" id="quantity" name="quantity" value="{{ old('quantity') ?? $product->quantity }}" class="form-control @error ('quantity') is-invalid @enderror">
                @error('quantity')
                   <div class="text-muted">{{ $message }}</div>
               @enderror
            </div>


        <div class="form-group">
            <label for="description" class="form-control-label">Deskripsi Barang</label>
            <textarea type="text" id="description" name="description" class="form-control ckeditor @error('description') is-invalid @enderror">{{ old('description') ?? $product->description  }}</textarea>
            @error('description')
                   <div class="text-muted">{{ $message }}</div>
               @enderror
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Edit Barang</button>
        </div>
       </form>
   </div>

@endsection

backend/pinstore/resources/views/pages/products/gallery.blade.php
@extends('layouts.default')
@section('title','Foto Barang')
@section('content')

    <div class="orders">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="box-title">Foto Barang</div>
                    </div>
                    <div class="card-body">
                        <div class="table-stats order-table ov-h">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <td>#</td>
                                        <td>Nama Barang</td>
                                        <td>Foto</td>
                                        <td>Default</td>
                                        <td>Action</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($items as $item)
                                        <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->product->name }}</td>
                                        <td>
                                            <img src="{{ url($item->photo) }}" alt="product gallery pinstore">
                                        </td>
                                        <td>{{ $item->is_default ? 'Ya' : 'Tidak'}}</td>
                                        <td>
                                            <form action="{{ route('product-galleries.destroy', $item->id) }}" class="d-inline" method="POST">
                                                @method('delete')
                                                @csrf
                                                <button class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
                                            </form>
                                        </td>
                                        @empty
                                            <td>
                                                <td colspan="5" class="text-center"><strong>Data yang anda cari tidak ada</strong></td>
                                            </td>
                                        </tr>
                                        @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

backend/pinstore/resources/views/pages/products/index.blade.php
@extends('layouts.default')
@section('title','Data Barang')
@section('content')

    <div class="orders">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="box-title">Daftar Barang</div>
                    </div>
                    <div class="card-body">
                        <div class="table-stats order-table ov-h">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <td>#</td>
                                        <td>Name</td>
                                        <td>Type</td>
                                        <td>Price</td>
                                        <td>Quantity</td>
                                        <td>Action</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($products as $product)
                                        <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $product->name }}</td>
                                        <td>{{ $product->type }}</td>
                                        <td>{{ $product->price }}</td>
                                        <td>{{ $product->quantity }}</td>
                                        <td>
                                            <a href="{{ route('products.gallery',$product->id) }}" class="btn btn-info btn-sm"><i class="fa fa-picture-o"></i></a>

                                            <a href="{{ route('products.edit', $product->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
                                            
                                            <form action="{{ route('products.destroy', $product->id) }}" class="d-inline" method="POST">
                                                @method('delete')
                                                @csrf
                                                <button class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
                                            </form>
                                        </td>
                                        @empty
                                            <td>
                                                <td colspan="5" class="text-center"><strong>Data yang anda cari tidak ada</strong></td>
                                            </td>
                                        </tr>
                                        @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection