backend/pinstore/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'DashboardController@index')->name('dashboard');
Route::get('transactions/{id}/set-status','TransactionController@status')->name('transactions.status');
Route::get('products/{id}/gallery','ProductController@gallery')->name('products.gallery');
Route::resource('products', 'ProductController');
Route::resource('product-galleries','ProductGalleryController');
Route::resource('transactions','TransactionController');

backend/pinstore/app/ProductGallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class ProductGallery extends Model
{

    use SoftDeletes;
    protected $fillable =[
        'products_id','photo','is_default'
    ];


    public function getPhotoAttribute($value)
    {
        return url('storage/' . $value);
    }

    public function product(){
        return $this->belongsTo(Product::class,'products_id','id');
    }
}

backend/pinstore/app/Http/Controllers/ProductGalleryController.php
<?php

namespace App\Http\Controllers;

use App\ProductGallery;
use App\Product;
use App\Http\Requests\ProductGalleryRequest;
use Illuminate\Http\Request;

class ProductGalleryController extends Controller
{
       /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = ProductGallery::with('product')->get();
        return view('pages.product-galleries.index',compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $products = Product::all('id','name');
        return view('pages.product-galleries.create',compact('products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductGalleryRequest $request)
    {
        $items = $request->all();
        $items['photo'] = $request->file('photo')->store('assets/product','public');

        ProductGallery::create($items);
        return redirect()->route('product-galleries.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ProductGallery  $productGallery
     * @return \Illuminate\Http\Response
     */
    public function show(ProductGallery $productGallery)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ProductGallery  $productGallery
     * @return \Illuminate\Http\Response
     */
    public function edit(ProductGallery $productGallery)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ProductGallery  $productGallery
     * @return \Illuminate\Http\Response
     */
    public function update(ProductGalleryRequest $request,  $id)
    {
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ProductGallery  $productGallery
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = ProductGallery::findOrFail($id)->delete();
        return redirect()->route('product-galleries.index');
    }
}

backend/pinstore/resources/views/pages/product-galleries/create.blade.php
@extends('layouts.default')
@section('title','Tambah Foto Barang')
@section('content')

   <div class="card">
       <div class="card-header"><strong>Tambah Foto Barang</strong></div>
   </div>
   <div class="card-body card-block">
       <form action="{{ route('product-galleries.store') }}" method="POST" enctype="multipart/form-data">
           @csrf
           <div class="form-group">
               <label for="name" class="form-control-label">Nama Barang</label>
               <select name="products_id" id="name" class="form-control @error('products_id') is-invalid @enderror">
                   @foreach ($products as $product)
                       <option value="{{ $product->id }}">{{ $product->name }}</option>
                   @endforeach
               </select>
               @error('products_id')
                   <div class="text-muted text-danger">{{ $message }}</div>
               @enderror
           </div>

           <div class="form-group">
                <label for="photo" class="form-control-label">Foto Barang</label>
                <input type="file" accept="image/*" id="photo" name="photo" value="{{ old('photo') }}" class="form-control @error('photo') is-invalid @enderror">
                @error('photo')
                   <div class="text-muted text-danger">{{ $message }}</div>
               @enderror
            </div>

            <div class="form-group">
                <label for="price" class="form-control-label">Default Barang</label>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="is_default" id="radio1" value="1" checked>
                <label class="form-check-label" for="radio1">
                    Ya
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="is_default" id="radio2" value="0">
                <label class="form-check-label" for="radio2">
                    Tidak
                </label>
              </div>
              @error('is_default')
                   <div class="text-muted text-danger">{{ $message }}</div>
               @enderror
            </div>



        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Tambah Barang</button>
        </div>
       </form>
   </div>

@endsection

backend/pinstore/resources/views/pages/product-galleries/index.blade.php
@extends('layouts.default')
@section('title','Data Barang')
@section('content')

<div class="orders">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="box-title">Foto Barang</div>
                </div>
                <div class="card-body">
                    <div class="table-stats order-table ov-h">
                        <table class="table">
                            <thead>
                                <tr>
                                    <td>#</td>
                                    <td>Nama Barang</td>
                                    <td>Foto</td>
                                    <td>Default</td>
                                    <td>Action</td>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($items as $item)
                                    <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $item->product->name }}</td>
                                    <td>
                                        <img src="{{ url($item->photo) }}" alt="product gallery pinstore">
                                    </td>
                                    <td>{{ $item->is_default ? 'Ya' : 'Tidak'}}</td>
                                    <td>
                                        <form action="{{ route('product-galleries.destroy', $item->id) }}" class="d-inline" method="POST">
                                            @method('delete')
                                            @csrf
                                            <button class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                    @empty
                                        <td>
                                            <td colspan="5" class="text-center"><strong>Data yang anda cari tidak ada</strong></td>
                                        </td>
                                    </tr>
                                    @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection