backend/pinstore/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'DashboardController@index')->name('dashboard');
Route::get('transactions/{id}/set-status','TransactionController@status')->name('transactions.status');
Route::get('products/{id}/gallery','ProductController@gallery')->name('products.gallery');
Route::resource('products', 'ProductController');
Route::resource('product-galleries','ProductGalleryController');
Route::resource('transactions','TransactionController');

backend/pinstore/app/Http/Controllers/API/TransactionController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Transaction;
use Illuminate\Http\Request;

class TransactionController extends Controller
{
    public function get(Request $request, $id){
        $product = Transaction::with('details.product')->find($id);

        if($product)
            return ResponseFormatter::success($product,'Data berhasil diambil');
        else
            return ResponseFormatter::error(null,'Data gagal diambil',404);
    }
}

backend/pinstore/app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Transaction;
use Illuminate\Http\Request;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    
    public function index()
    {
        $items = Transaction::all();
        return view('pages.transaction.index',compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show($id){
        $item = Transaction::with('details.product')->findOrFail($id);
        return view('pages.transaction.show',compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$id)
    {
        $transaction = Transaction::findOrFail($id);
        return view('pages.transaction.edit',compact('transaction'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $transaction = Transaction::findOrFail($id);
        $transaction->update($request->all());
        return redirect()->route('transactions.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        //
    }

    public function status(Request $request, $id){
        $item = Transaction::findOrFail($id);
        $item['transaction_status'] = $request->status;
        $item->save();
        return redirect()->back();
    }

}

backend/pinstore/resources/views/pages/transaction/edit.blade.php
@extends('layouts.default')
@section('title','Edit Transaksi')
@section('content')

   <div class="card">
       <div class="card-header"><strong>Edit Transaksi | {{ $transaction->uuid }}</strong></div>
   </div>
   <div class="card-body card-block">
       <form action="{{ route('transactions.update',$transaction->id) }}" method="POST">
        @method('PUT')
           @csrf
           <div class="form-group">
               <label for="name" class="form-control-label">Nama Barang</label>
               <input type="text" id="name" name="name" value="{{ old('name') ?? $transaction->name }}" class="form-control @error('name') is-invalid @enderror">
               @error('name')
                   <div class="text-muted">{{ $message }}</div>
               @enderror
           </div>

           <div class="form-group">
                <label for="email" class="form-control-label">Email</label>
                <input type="email" id="email" name="email" value="{{ old('email') ?? $transaction->email  }}" class="form-control @error ('email') is-invalid @enderror">
                @error('email')
                   <div class="text-muted">{{ $message }}</div>
               @enderror
            </div>

            <div class="form-group">
                <label for="number" class="form-control-label">Nomor</label>
                <input type="number" id="number" name="number" value="{{ old('number') ?? $transaction->number  }}" class="form-control @error ('number') is-invalid @enderror">
                @error('number')
                   <div class="text-muted">{{ $message }}</div>
               @enderror
            </div>


            <div class="form-group">
                <label for="address" class="form-control-label">Alamat</label>
                <input type="text" id="address" name="address" value="{{ old('address') ?? $transaction->address }}" class="form-control @error ('address') is-invalid @enderror">
                @error('address')
                   <div class="text-muted">{{ $message }}</div>
               @enderror
            </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Edit Transaksi</button>
        </div>
       </form>
   </div>

@endsection

backend/pinstore/resources/views/pages/transaction/index.blade.php
@extends('layouts.default')
@section('title','Data Barang')
@section('content')

    <div class="orders">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="box-title">Daftar Barang</div>
                    </div>
                    <div class="card-body">
                        <div class="table-stats order-table ov-h">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <td>#</td>
                                        <td>Nama</td>
                                        <td>Email</td>
                                        <td>Nomor</td>
                                        <td>Total Transaksi</td>
                                        <td>Status</td>
                                        <td>Action</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($items as $item)
                                        <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->name }}</td>
                                        <td>{{ $item->email }}</td>
                                        <td>{{ $item->number }}</td>
                                        <td>{{ $item->transaction_total }}</td>
                    
                                        <td>
                                            @if($item->transaction_status == 'SUCCESS')
                                                <span class="badge badge-success badge-pill">
                                            @elseif($item->transaction_status == 'PENDING')
                                                <span class="badge badge-secondary badge-pill">
                                            @elseif($item->transaction_status == 'FAILED')
                                                <span class="badge badge-danger badge-pill">
                                            @else
                                                <span>
                                            @endif
                                                {{ $item->transaction_status }}
                                                </span>
                                        </td>

                                        <td>
                                            @if($item->transaction_status == 'PENDING')
                                                <a href="{{ route('transactions.status',$item->id) }}?status=SUCCESS" class="btn btn-success btn-sm">
                                                    <i class="fa fa-check"></i>
                                                </a>
                                                <a href="{{ route('transactions.status',$item->id) }}?status=FAILED" class="btn btn-danger btn-sm">
                                                    <i class="fa fa-times"></i>
                                                </a>
                                            @endif

                                            <a href="#mymodal" data-remote="{{ route('transactions.show',$item->id) }}" data-toggle="modal" data-target="#mymodal" data-title="Detail Transaksi {{ $item->uuid }}" class="btn btn-info btn-sm"><i class="fa fa-eye"></i></a>
                                            
                                            <a href="{{ route('transactions.edit', $item->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
                                            
                                            <form action="{{ route('transactions.destroy', $item->id) }}" class="d-inline" method="POST">
                                                @method('delete')
                                                @csrf
                                                <button class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
                                            </form>
                                        </td>
                                        @empty
                                            <td>
                                                <td colspan="7" class="text-center"><strong>Data yang anda cari tidak ada</strong></td>
                                            </td>
                                        </tr>
                                        @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

backend/pinstore/resources/views/pages/transaction/show.blade.php
<table class="table table-bordered">
    <tr>
        <th>Nama</th>
        <td>{{ $item->name }}</td>
    </tr>
    <tr>
        <th>Email</th>
        <td>{{ $item->email }}</td>
    </tr>
    <tr>
        <th>Nomor</th>
        <td>{{ $item->number }}</td>
    </tr>
    <tr>
        <th>Alamat</th>
        <td>{{ $item->address }}</td>
    </tr>
    <tr>
        <th>Total Transaksi</th>
        <td>{{ $item->transaction_total }}</td>
    </tr>
    <tr>
        <th>Status Transaksi</th>
        <td>{{ $item->transaction_status }}</td>
    </tr>
    <tr>
        <th>Pembelian Produk</td>
        <td>
            <table class="table table-bordered w-100">
                <tr>
                    <th>Nama</th>
                    <th>Tipe</th>
                    <th>Harga</th>
                </tr>
                @foreach($item->details as $detail )
                <tr>
                    <td>{{ $detail->product->name }}</td>
                    <td>{{ $detail->product->type }}</td>
                    <td>{{ $detail->product->price }}</td>
                </tr>
                @endforeach
            </table>
        </td>
    </tr>
</table>
<div class="row">
    <div class="col-4"><a href="{{ route('transactions.status',$item->id) }}?status=SUCCESS" class="btn btn-success btn-block"><i class="fa fa-check"></i>Set Sukses</a></div>
    <div class="col-4"><a href="{{ route('transactions.status',$item->id) }}?status=PENDING" class="btn btn-secondary btn-block"><i class="fa fa-times"></i>Set Pending</a></div>
    <div class="col-4"><a href="{{ route('transactions.status',$item->id) }}?status=FAILED" class="btn btn-warning btn-block"><i class="fa fa-spinner"></i>Set Gagal</a></div>
</div>